[package]
name = "dod-tools"
version = "0.4.2"
edition = "2021"

[dependencies]
dem = "0.2.2"
eframe = "0.31.0"
egui = "0.31.0"
egui_extras = "0.31.0"
egui-file-dialog = "0.9.0"
filetime = "0.2.25"
humantime = "2.1.0"
nom = "8.0.0"
tabled = "0.18.0"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
uuid = { version = "1.13.2", features = ["v4"] }
