[package]
name = "dod-tools"
version = "0.5.0"
edition = "2024"

[dependencies]
dem = "0.2.3"
eframe = "0.31.1"
egui = "0.31.1"
egui_extras = "0.31.1"
egui-file-dialog = "0.9.0"
egui_plot = "0.31.0"
filetime = "0.2.25"
humantime = "2.2.0"
nom = "8.0.0"
tabled = "0.18.0"
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }
uuid = { version = "1.16.0", features = ["v4"] }
